[settings]
python.uv_venv_auto = true

[tools]
python = "3.13.7"
uv = "latest"

[env]
_.file = ".env"

[tasks.install]
description = "Install project dependencies"
run = "uv sync --dev"

[tasks.dev]
description = "Run a hot reloading dev server"
run = "uv run uvicorn momento_mori.app:app --reload"

[tasks.format]
description = "Format Python code"
run = "uv run ruff format"

[tasks.lint]
description = "Lint Python code"
run = "uv run ruff check"

[tasks.lint-fix]
description = "Lint and fix Python code"
run = "uv run ruff check --fix"

[tasks.test]
description = "Run tests"
run = "uv run pytest"
